### ISSUE TITLE
"spoofable" Repeated Twice within JSON Returned by IP Context v2

### ISSUE THREAD

**Issue by cmlh** [GreyNoise-Intelligence/greynoise-maltego#13]
The `spoofable` field appears twice in the JSON returned from [IP Context v2](https://developer.greynoise.io/reference#noisecontextip-1)

`{`
`"spoofable"`
`"metadata"{`
`    "spoofable"`
`    }`
`}`

There is also no mention of `spoofable` field within the documentation of [IP Context v2](https://developer.greynoise.io/reference#noisecontextip-1) too.

**Comment by bradchiappetta** [comment]
This is an API side bug, which we have reported and are looking into.  Closing as unrelated to this integration.
