### ISSUE TITLE
"vpn" and "vpn_service" Repeated Twice within JSON Returned by IP Context v2

### ISSUE THREAD

**Issue by cmlh** [GreyNoise-Intelligence/greynoise-maltego#14]
The `vpn` and `vpn_service` fields appear twice in the JSON returned from [IP Context v2](https://developer.greynoise.io/reference#noisecontextip-1)

`{`
`"metadata"{`
`    "vpn"`
`    "vpn_service"`
`    }`
`"vpn"`
`"vpn_service"`
`}`

There is also no mention of `vpn` and `vpn_service` fields within the documentation of [IP Context v2](https://developer.greynoise.io/reference#noisecontextip-1) too.

**Comment by bradchiappetta** [comment]
This is an API side bug, which we have reported and are looking into. Closing as unrelated to this integration.
