### ISSUE TITLE
Support Ping Service

### ISSUE THREAD

**Issue by cmlh** [GreyNoise-Intelligence/greynoise-maltego#17]
### Is your proposal related to a problem?

The [Ping Service](https://developer.greynoise.io/reference/ping-service) is not supported by Maltego.

### Describe the solution you'd like

Include support for the [Ping Service](https://developer.greynoise.io/reference/ping-service) for Maltego.

### Describe alternatives you've considered

There are no other alternatives to the [Ping Service](https://developer.greynoise.io/reference/ping-service).

### Additional context

I will submit a Pull Request.

**Comment by bradchiappetta** [comment]
There is no need to include the Ping service, as it doesn't provide any value in the context of this transform.
