### ISSUE TITLE
Support Community API

### ISSUE THREAD

**Issue by cmlh** [GreyNoise-Intelligence/greynoise-maltego#18]
### Is your proposal related to a problem?

The [Community API](https://developer.greynoise.io/reference/community-api) is not supported by Maltego.

### Describe the solution you'd like

Support the [Community API](https://developer.greynoise.io/reference/community-api) with Maltego.

### Describe alternatives you've considered

There are no alternatives to the  [Community API](https://developer.greynoise.io/reference/community-api).

### Additional context

I'll submit a Pull Request.

**Comment by bradchiappetta** [comment]
This repo has already been repurposed to support a GreyNoise Community transform, which will be independent of the contribute integration you are building.  You can maintain your version of the repo independently for the work you are doing since they are two separate initiatives at this point.
