### ISSUE TITLE
No csr.greynoiseclassification Entity

### ISSUE THREAD

**Issue by cmlh** [GreyNoise-Intelligence/greynoise-maltego#6]
The [csr.greynoiseclassification](https://github.com/GreyNoise-Intelligence/greynoise-maltego/blob/master/transforms/GreyNoiseIPContext.py#L20) Entity is not included within a Maltego Configuration File.

Neither is a Maltego Configuration File defined within the git repository.

The solution is to create a Maltego Configuration File that imports the [csr.greynoiseclassification](https://github.com/GreyNoise-Intelligence/greynoise-maltego/blob/master/transforms/GreyNoiseIPContext.py#L20) Entity.

This issue may be superseded since commit https://github.com/GreyNoise-Intelligence/greynoise-maltego/commit/e6405924065d523ddfea3c7fe3d7be71677711d1

**Comment by bradchiappetta** [comment]
@cmlh : can you review https://github.com/GreyNoise-Intelligence/greynoise-maltego/pull/9 and let me know if this is what you were looking for with these requests?

**Comment by cmlh** [comment]
@bradchiappetta

My preference would be to replace with these two Entities with `maltego.Phrase` for now but I can't make a recommendation till I review Pull Request #9

Just merge #9 and I'll make any changes afterwards?

**Comment by cmlh** [comment]
👍
