### ISSUE TITLE
No csr.greynoisetag Entity

### ISSUE THREAD

**Issue by cmlh** [GreyNoise-Intelligence/greynoise-maltego#7]
The [csr.greynoisetag](https://github.com/GreyNoise-Intelligence/greynoise-maltego/blob/master/transforms/GreyNoiseIPContext.py#L23) Entity is not included within a Maltego Configuration File.

Neither is a Maltego Configuration File defined within the git repository.

The solution is to create a Maltego Configuration File that imports the [csr.greynoisetag](https://github.com/GreyNoise-Intelligence/greynoise-maltego/blob/master/transforms/GreyNoiseIPContext.py#L23) Entity.

This issue may be superseded since commit https://github.com/GreyNoise-Intelligence/greynoise-maltego/commit/e6405924065d523ddfea3c7fe3d7be71677711d1 and is similar to Issue #6

**Comment by bradchiappetta** [comment]
Fixed as part of #9
